name: Terraform

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checkov-job:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Prisma Cloud
    env:
      PRISMA_API_URL: https://api0.prismacloud.io/
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Run Prisma Cloud action
        id: Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: '.'
          soft_fail: true
          api-key: ${{ secrets.BC_API_KEY }}
      - name: Expose report
        uses: actions/upload-artifact@v3
        with:
          name: SARIF results
          path: results.sarif
      - uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif
          
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.8.3
        cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}

    - name: Set up Terraform credentials
      run: |
        mkdir -p $HOME/.terraform.d
        echo "{\"credentials\":{\"app.terraform.io\":{\"token\":\"${{ secrets.TFC_TOKEN }}\"}}}" > $HOME/.terraform.d/credentials.tfrc.json
        
    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
